// ------- Config Google API --------
const String GOOGLE_API_KEY = 'AIzaSyDR62lMu_ZOGtuvlxTJWl8jm2ciDc2Smmo';

// ------- Config Endpoint ---------
const String BASE_URL = "https://mobile.techthinkhub.id/api";
// const String BASE_URL = "https://be.techthinkhub.id/api";
const String BASE_URL_RSS = "https://bengkelly.co.id";
const String BASE_URL_FLEET = "https://fleetmaintenance.co.id";
const String LOGIN_ENDPOINT = "$BASE_URL/customer/login";
const String REGISTER_ENDPOINT = "$BASE_URL/register-kendaraan";
const String GET_MERK_ENDPOINT = "$BASE_URL/merk";
const String TYPE_BY_MERK_ENDPOINT = "$BASE_URL/tipe";
const String RSS_ENDPOINT = "$BASE_URL_RSS/wp-json/wp/v2/posts?_embed";
const String GET_LOCATION_ENDPOINT = "$BASE_URL/get-lokasi";
const String GET_VEHICLE = "$BASE_URL/customer-kendaraan";
const String CREATE_BOOKING = "$BASE_URL/booking/book-rest-area";
const String CREATE_VEHICLE = "$BASE_URL/customer-create-kendaraan";
const String GET_HISTORY_ENDPOINT = "$BASE_URL/history";
const String GET_PROFILE_ENDPOINT = "$BASE_URL/customer-get-profile";
const String UPDATE_PROFILE_ENDPOINT = "$BASE_URL/customer-update-profile";
const String SEND_OTP_ENDPOINT = "$BASE_URL/customer/kirim-otp";
const String VERIFY_OTP_ENDPOINT = "$BASE_URL/customer/verify-otp";
const String RESET_PASSWORD_ENDPOINT = "$BASE_URL/customer/reset-password";
const String GENERAL_CHECK_UP = "$BASE_URL/general-checkup";
const String CHANGE_PASSWORD = "$BASE_URL/customer/ubah-password";
const String CREATE_EMERGENCY = "$BASE_URL/emergency-service";
const String GET_NEWS_FLEET = "$BASE_URL_FLEET/wp-json/wp/v2/posts?_embed";
const String GET_NEWS_FLEED = "$BASE_URL_FLEET/feed/";
const String GET_JENIS_SERVICE = "$BASE_URL/get-jenis-service";
// ------- Local Storage Key ---------
const String APP_OAUTHDATA_KEY = "oAuthData";
const String ACTIVATION_LOCATION = "locationService";
const String ACTIVATION_NOTIFICATION = "NotificationService";
const String VEHICLE_ID = "idVehicle";
const String VEHICLE = "vehicle";
const String LOCATION_HOME = "location";
// ------- Image Assets ---------
const double IMAGES_HEIGHT = 180;
const String BACKGROUND_WELCOME = "assets/bg_welcome.png";
const String LOGO = "assets/logo.png";
const String GOOGLE_IC = "assets/google.png";
const String FB_IC = "assets/facebook.png";
const String APPLE_IC = "assets/apple.png";
const String SUCCESS_IC = "assets/ic_success.png";
const String ERROR_IC = "assets/ic_error.png";
const String WARNING_IC = "assets/ic_warning.png";
const String SUCCESS_MARK = "assets/success_logo.png";
const String IC_HOME = "assets/ic_home.png";
const String IC_NEWS = "assets/ic_news.png";
const String IC_HISTORY = "assets/ic_history.png";
const String IC_PROFILE = "assets/ic_profile.png";
const String IC_BOOKING = "assets/ic_booking.png";
const String IC_LOCATION = "assets/ic_location.png";
const String IC_CHAT = "assets/ic_chat.png";
const String BANNER = "assets/banner.png";
const String SLIDERS = "assets/slider1.png";
const String SLIDERS2 = "assets/slide2.jpg";
const String IC_FLOATING = "assets/floating.png";
const String BOOKING_SERVICE = "assets/booking_service.png";
const String ALL = "assets/lihat_semua.png";
const String IC_REPAIR = "assets/ic_repair.png";
const String IC_SEE_ALL = "assets/ic_see_all.png";
const String IC_EMERGENCY = "assets/ic_emergency.png";
const String IC_TIMER = "assets/ic_timer.png";
const String DUMMY_IMAGE = "assets/product.png";
const String DUMMY_PROMO_IMAGE = "assets/promo.png";
const String DUMMY_DEALS_IMAGE = "assets/deals.png";
const String DUMMY_AVATAR = "assets/avatar.png";
const String EDIT = "assets/edit.png";
const String IC_CAR = "assets/car.png";
const String IC_POCKET = "assets/pocket.png";
const String IC_HELP = "assets/help.png";
const String IC_SETTINGS = "assets/settings.png";
const String IC_LOGOUT = "assets/logout.png";
const String IC_NOTIFICATION = "assets/notification_alert.png";
const String IC_LOCATION_ALERT = "assets/location_alert.png";
const String IC_ARROW_DOWN = "assets/arrow_down.png";
const String IC_CENTER_LOC = "assets/ic_center_loc.png";
const String IC_SORT = "assets/ic_sort.png";
const String IC_NEWS_SLIDE = "assets/news.png";
const String IC_NEWS_ITEM = "assets/news_item.png";
const String IC_NOTIF_ITEM = "assets/ic_notif_item.png";
const String IC_NOTIF_SUCCESS = "assets/ic_success_notif.png";
const String IC_CONTACT = "assets/contact.png";
const String IC_REST = "assets/rest_area.png";
const String PROMO1 = "assets/tenant_dummy/promo.png";
const String PROMO = "assets/promo1.jpeg";
const String DEALS1 = "assets/tenant_dummy/deals1.png";
const String BANNDER1 = "assets/tenant_dummy/banner1.png";
const String FLOATING_EMERGENCY = "assets/floating_emergency.png";
const String LOCATION_MARK = "assets/Location_mark.png";
const String IC_NEARBY = 'assets/ic_nearby.png';
const String DROP_PIN = 'assets/drop_pin_bengkelly.png';
const String DUMMY_IMAGE_NEW = 'assets/dummy_image.png';
const String REST_AREA_575 = 'assets/rest_area_575.png';
const String REST_AREA_379 = 'assets/rest_area_379.png';
const String REST_AREA_389 = 'assets/rest_area_389.jpg';
const String REST_AREA_228a = 'assets/288a/s228a-1.jpg';
const String REST_AREA_228a_2 = 'assets/288a/s228a-2.jpg';
const String REST_AREA_228a_3 = 'assets/288a/s228a-3.jpg';
const String REST_AREA_319b_ = 'assets/319b/s319b-1.jpg';
const String REST_AREA_319b_2_ = 'assets/319b/s319b-2.jpg';
const String REST_AREA_319b_3_ = 'assets/319b/s319b-3.jpg';
const String REST_AREA_319 = 'assets/319b.jpg';
const String OLI4L = 'assets/oli4l.png';
const String OLI1L = 'assets/oli1l.jpeg';

// ------- Icons Assets ---------
const String STAR = 'assets/star.png';
const String SAFETY = 'assets/safety.png';


const int PER_PAGE = 0;
const double SCROLLTHRESHOLD = 200;


